[package]
name = "sdl"
version = "0.1.0"
authors = ["Owner Name <owner_name@email.com>"]
edition = "2018"

[dependencies]
sdl2 = "0.34.3"
gl = "0.14.0"
cgmath = "0.18.0"
c_str_macro = "1.0.2"
imgui = "0.6.1"
imgui-sdl2 = "0.13.0"
imgui-opengl-renderer = "0.10.0"
